"""Assemble the final Markdown report and JSON export from the pipeline state.

Assembly is deterministic: the LLM writes prose *sections*; the skeleton, tables,
table of contents and appendices are built here from the consolidated items, so
structural facts (owners, due dates, counts, segment references) are exact.
Segment ids emitted by the model are validated against the real transcript, so a
hallucinated citation is dropped rather than shown.
"""

from __future__ import annotations

import json
from datetime import date

from .. import __version__
from ..model.extraction import CATEGORIES
from ..model.transcript import TranscriptInventory
from .lint import lint_markdown, md_anchor, md_cell


def _get(state, key, default=None):
    return state.get(key, default) if isinstance(state, dict) else getattr(state, key, default)


def _valid_sids(inv: TranscriptInventory) -> set[str]:
    return set(inv.by_sid().keys())


def _refs(item, valid: set[str]) -> str:
    ids = [s for s in (getattr(item, "segment_ids", None) or []) if s in valid]
    return ", ".join(ids)


# --------------------------------------------------------------------------- #
# Markdown report
# --------------------------------------------------------------------------- #

def render_report(state) -> str:
    inv: TranscriptInventory = _get(state, "inventory")
    synthesis = _get(state, "synthesis")
    items: dict = _get(state, "items", {}) or {}
    valid = _valid_sids(inv)

    title = (synthesis.title if synthesis else "") or inv.title_hint or "Meeting"
    sections: list[tuple[str, str]] = []

    sections.append(("Executive summary", synthesis.executive_summary if synthesis else ""))
    sections.append(("Meeting overview", _overview(state, inv, synthesis)))
    sections.append(("Participants", _participants(inv, synthesis)))
    sections.append(("Detailed summary", synthesis.detailed_summary if synthesis else ""))
    sections.append(("Topics discussed", _topics(items.get("topics"), valid)))
    sections.append(("Decisions", _decisions(items.get("decisions"), valid)))
    sections.append(("Action items", _action_items(items.get("action_items"), valid)))
    sections.append(("Open questions", _open_questions(items.get("open_questions"), valid)))
    sections.append(("Risks and blockers", _risks(items.get("risks"), valid)))
    sections.append(("Key facts and figures", _key_facts(items.get("key_facts"), valid)))
    sections.append(("Dates and deadlines", _key_dates(items.get("key_dates"), valid)))
    sections.append(("People and entities", _entities(items.get("entities"), valid)))
    sections.append(("Notable quotes", _quotes(items.get("quotes"), valid)))
    sections.append(("Disagreements", _disagreements(items.get("disagreements"), valid)))
    sections.append(("Glossary", _glossary(items.get("glossary"), valid)))
    sections.append(("Next steps", _next_steps(synthesis)))
    sentiment = synthesis.overall_sentiment if synthesis else ""
    if sentiment:
        sections.append(("Overall sentiment", sentiment))
    sections.append(("Appendix: analysis notes", _appendix(state, inv, items)))

    out: list[str] = [f"# {title} — Meeting Report", ""]
    out.append(
        f"Generated by meeting-assistant v{__version__} on {date.today().isoformat()}. "
        "This report was produced by multi-pass analysis of the transcript; every item "
        "cites the transcript segments (Sxx) it was drawn from."
    )
    out.append("")
    out.append("## Contents")
    out.append("")
    for heading, _ in sections:
        out.append(f"- [{heading}](#{md_anchor(heading)})")
    for heading, body in sections:
        out.append("")
        out.append(f"## {heading}")
        out.append("")
        out.append((body or "").strip() or "None identified.")
    return lint_markdown("\n".join(out))


def _overview(state, inv: TranscriptInventory, synthesis) -> str:
    rounds = _get(state, "rounds_done", 0)
    item_count = _get(state, "item_count", 0)
    rows = [
        ("Meeting type", (synthesis.meeting_type if synthesis else "") or "-"),
        ("Source", inv.source_file or "(inline text)"),
        ("Transcript format", inv.source_format),
        ("Time span", inv.duration or "-"),
        ("Participants", str(len(inv.speakers)) if inv.speakers else "not labeled"),
        ("Segments", str(len(inv.segments))),
        ("Words", str(inv.total_words)),
        ("Review passes", str(rounds)),
        ("Items extracted", str(item_count)),
    ]
    lines = ["| Item | Value |", "|------|-------|"]
    lines += [f"| {md_cell(k)} | {md_cell(v)} |" for k, v in rows]
    return "\n".join(lines)


def _participants(inv: TranscriptInventory, synthesis) -> str:
    roles = {p.name: p.role for p in (synthesis.participants if synthesis else [])}
    if not inv.speakers and not roles:
        return "Speakers were not labeled in this transcript."
    lines = ["| Participant | Role / contribution | Turns | Words |", "|-------------|---------------------|-------|-------|"]
    if inv.speakers:
        for sp in inv.speakers:
            lines.append(f"| {md_cell(sp.name)} | {md_cell(roles.get(sp.name, '') or '-')} | {sp.turns} | {sp.words} |")
    else:
        for name, role in roles.items():
            lines.append(f"| {md_cell(name)} | {md_cell(role or '-')} | - | - |")
    return "\n".join(lines)


def _topics(rows, valid) -> str:
    if not rows:
        return ""
    lines = ["| Topic | Summary | Segments |", "|-------|---------|----------|"]
    for t in rows:
        lines.append(f"| {md_cell(t.title)} | {md_cell(t.summary) or '-'} | {md_cell(_refs(t, valid)) or '-'} |")
    return "\n".join(lines)


def _decisions(rows, valid) -> str:
    if not rows:
        return ""
    lines = ["| Decision | Rationale | Decided by | Segments |", "|----------|-----------|------------|----------|"]
    for d in rows:
        lines.append(
            f"| {md_cell(d.decision)} | {md_cell(d.rationale) or '-'} | {md_cell(d.decided_by) or '-'} | {md_cell(_refs(d, valid)) or '-'} |"
        )
    return "\n".join(lines)


def _action_items(rows, valid) -> str:
    if not rows:
        return ""
    lines = ["| Task | Owner | Due | Priority | Status | Segments |",
             "|------|-------|-----|----------|--------|----------|"]
    for a in rows:
        lines.append(
            f"| {md_cell(a.task)} | {md_cell(a.owner) or '-'} | {md_cell(a.due) or '-'} | "
            f"{md_cell(a.priority) or '-'} | {md_cell(a.status) or '-'} | {md_cell(_refs(a, valid)) or '-'} |"
        )
    return "\n".join(lines)


def _open_questions(rows, valid) -> str:
    if not rows:
        return ""
    out = []
    for q in rows:
        by = f" (raised by {md_cell(q.raised_by)})" if q.raised_by else ""
        ctx = f" — {md_cell(q.context)}" if q.context else ""
        ref = f" [{_refs(q, valid)}]" if _refs(q, valid) else ""
        out.append(f"- {md_cell(q.question)}{by}{ctx}{ref}")
    return "\n".join(out)


def _risks(rows, valid) -> str:
    if not rows:
        return ""
    lines = ["| Risk / blocker | Severity | Mitigation | Segments |", "|----------------|----------|------------|----------|"]
    for r in rows:
        lines.append(
            f"| {md_cell(r.description)} | {md_cell(r.severity) or '-'} | {md_cell(r.mitigation) or '-'} | {md_cell(_refs(r, valid)) or '-'} |"
        )
    return "\n".join(lines)


def _key_facts(rows, valid) -> str:
    if not rows:
        return ""
    out = []
    for f in rows:
        cat = f" ({md_cell(f.category)})" if f.category else ""
        ref = f" [{_refs(f, valid)}]" if _refs(f, valid) else ""
        out.append(f"- {md_cell(f.fact)}{cat}{ref}")
    return "\n".join(out)


def _key_dates(rows, valid) -> str:
    if not rows:
        return ""
    lines = ["| When | What | Segments |", "|------|------|----------|"]
    for d in rows:
        lines.append(f"| {md_cell(d.when)} | {md_cell(d.what)} | {md_cell(_refs(d, valid)) or '-'} |")
    return "\n".join(lines)


def _entities(rows, valid) -> str:
    if not rows:
        return ""
    by_kind: dict[str, list] = {}
    for e in rows:
        by_kind.setdefault(e.kind or "other", []).append(e)
    out = []
    for kind in sorted(by_kind):
        out.append(f"### {kind.capitalize()}")
        out.append("")
        for e in by_kind[kind]:
            note = f" — {md_cell(e.note)}" if e.note else ""
            ref = f" [{_refs(e, valid)}]" if _refs(e, valid) else ""
            out.append(f"- {md_cell(e.name)}{note}{ref}")
        out.append("")
    return "\n".join(out).strip()


def _quotes(rows, valid) -> str:
    if not rows:
        return ""
    out = []
    for q in rows:
        who = f" — {md_cell(q.speaker)}" if q.speaker else ""
        ref = f" [{_refs(q, valid)}]" if _refs(q, valid) else ""
        out.append(f"> {md_cell(q.text)}{who}{ref}")
    return "\n\n".join(out)


def _disagreements(rows, valid) -> str:
    if not rows:
        return ""
    out = []
    for d in rows:
        pos = f" Positions: {md_cell(d.positions)}." if d.positions else ""
        res = f" Resolution: {md_cell(d.resolution)}." if d.resolution else ""
        ref = f" [{_refs(d, valid)}]" if _refs(d, valid) else ""
        out.append(f"- **{md_cell(d.topic)}**.{pos}{res}{ref}")
    return "\n".join(out)


def _glossary(rows, valid) -> str:
    if not rows:
        return ""
    lines = ["| Term | Definition |", "|------|------------|"]
    for g in rows:
        lines.append(f"| {md_cell(g.term)} | {md_cell(g.definition) or '-'} |")
    return "\n".join(lines)


def _next_steps(synthesis) -> str:
    if not synthesis or not synthesis.next_steps:
        return ""
    return "\n".join(f"- {md_cell(s)}" for s in synthesis.next_steps)


def _appendix(state, inv: TranscriptInventory, items: dict) -> str:
    rounds = _get(state, "rounds_done", 0)
    rescued = _get(state, "rescued", {}) or {}
    gap_notes = _get(state, "gap_notes", []) or []
    warnings = _get(state, "warnings", []) or []
    signals = _get(state, "signals", {}) or {}

    lines: list[str] = []
    lines.append(
        f"The transcript ({inv.total_words} words, {len(inv.segments)} segments) was reviewed in "
        f"{rounds} full pass(es) over {len(inv.chunks)} overlapping chunk(s). Each pass after the first "
        "re-read the whole transcript looking only for items earlier passes had missed."
    )
    counts = ", ".join(f"{label.lower()}: {len(items.get(field) or [])}" for field, label, _n in CATEGORIES)
    lines += ["", f"Items by category — {counts}."]

    if rescued:
        rescued_str = ", ".join(f"{k}: +{v}" for k, v in rescued.items())
        lines += ["", f"The gap-fill agent rescued additional items after synthesis ({rescued_str})."]
    if signals:
        lines += ["", "### Signal coverage (deterministic cue scan)", ""]
        lines += [f"- {cat}: {len(hits)} cue(s) detected" for cat, hits in signals.items()]
    if gap_notes:
        lines += ["", "### Gap-fill queries", ""]
        lines += [f"- {md_cell(q)}" for q in gap_notes]
    if warnings:
        lines += ["", "### Analysis warnings", ""]
        lines += [f"- {md_cell(w)}" for w in warnings]
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# JSON export
# --------------------------------------------------------------------------- #

def render_json(state) -> str:
    inv: TranscriptInventory = _get(state, "inventory")
    synthesis = _get(state, "synthesis")
    items: dict = _get(state, "items", {}) or {}

    payload = {
        "title": (synthesis.title if synthesis else "") or inv.title_hint or "Meeting",
        "meeting_type": synthesis.meeting_type if synthesis else "",
        "generated_by": f"meeting-assistant v{__version__}",
        "generated_on": date.today().isoformat(),
        "source": {
            "file": inv.source_file,
            "format": inv.source_format,
            "segments": len(inv.segments),
            "words": inv.total_words,
            "duration": inv.duration,
            "review_passes": _get(state, "rounds_done", 0),
        },
        "participants": [
            {"name": sp.name, "turns": sp.turns, "words": sp.words} for sp in inv.speakers
        ],
        "summary": {
            "executive_summary": synthesis.executive_summary if synthesis else "",
            "detailed_summary": synthesis.detailed_summary if synthesis else "",
            "overall_sentiment": synthesis.overall_sentiment if synthesis else "",
            "next_steps": synthesis.next_steps if synthesis else [],
        },
        "items": {
            field: [item.model_dump() for item in (items.get(field) or [])]
            for field, _l, _n in CATEGORIES
        },
        "warnings": _get(state, "warnings", []) or [],
    }
    return json.dumps(payload, indent=2, ensure_ascii=False)
